import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#4d8eff",
        "background": "#101415",
        "secondary-fixed-dim": "#c4c1fb",
        "tertiary-fixed": "#acedff",
        "on-primary": "#002e6a",
        "on-tertiary": "#003640",
        "surface-container-lowest": "#0b0f10",
        "on-secondary-container": "#b3afe9",
        "surface-container-low": "#191c1e",
        "surface": "#101415",
        "surface-tint": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "surface-container": "#1d2022",
        "on-tertiary-fixed": "#001f26",
        "on-secondary-fixed": "#181445",
        "secondary": "#c4c1fb",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#005ac2",
        "outline-variant": "#424754",
        "on-secondary-fixed-variant": "#444173",
        "error-container": "#93000a",
        "on-tertiary-container": "#002f38",
        "on-error": "#690005",
        "inverse-surface": "#e0e3e5",
        "on-background": "#e0e3e5",
        "surface-bright": "#363a3b",
        "inverse-on-surface": "#2d3133",
        "tertiary": "#4cd7f6",
        "on-secondary": "#2d2a5b",
        "surface-container-highest": "#323537",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-surface": "#e0e3e5",
        "on-surface-variant": "#c2c6d6",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#101415",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-container-high": "#272a2c",
        "tertiary-container": "#009eb9",
        "surface-variant": "#323537",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "error": "#ffb4ab",
        "secondary-container": "#444173",
        "secondary-fixed": "#e3dfff",
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'slide-up': { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'glow-pulse': { '0%, 100%': { boxShadow: '0 0 15px rgba(76, 215, 246, 0.4)' }, '50%': { boxShadow: '0 0 30px rgba(76, 215, 246, 0.8)' } },
        shimmer: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'slide-up': 'slide-up 0.6s ease-out forwards',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        shimmer: 'shimmer 2s infinite',
      },
    },
  },
  plugins: [],
};

export default config;

